# Generated by Django 4.1.1 on 2022-10-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=200)),
                ('Nearest_police_post', models.CharField(max_length=200)),
                ('summary_of_crime', models.TextField()),
                ('evidence', models.FileField(upload_to='')),
            ],
        ),
    ]
